import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import { TestScreen } from "./components";
import Screen from './components/layout/screen';
import { GateProvider } from "./context/gate.context";
import { ConnectionProvider } from "./context/connection.context";
import { MetricsProvider } from "./context/metrics.context";
import { ThemeProvider } from "./context/theme.context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Optima",
  description: "Generated by create next app",
};

const TESTING = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (TESTING) {
    return (
      <ThemeProvider>
        <GateProvider>
            <TestScreen />
        </GateProvider>
      </ThemeProvider>
    );
  } else {
    return (
      <ThemeProvider>
        <GateProvider>
          <ConnectionProvider>
            <MetricsProvider>
              <Screen>
                {children}
              </Screen>
            </MetricsProvider>
          </ConnectionProvider>
        </GateProvider>
      </ThemeProvider>
    );
  }
}
